sudo: required
services:
    - docker

before_install:
    - docker build -t gkaframanis/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gkaframanis/react-test npm run test

after_success:
    - docker build -t gkaframanis/multi-client ./client
    - docker build -t gkaframanis/multi-nginx ./nginx
    - docker build -t gkaframanis/multi-server ./server
    - docker build -t gkaframanis/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub 
    - docker push gkaframanis/multi-client
    - docker push gkaframanis/multi-nginx
    - docker push gkaframanis/multi-server
    - docker push gkaframanis/multi-worker